Gab.Web/Controllers/FeedsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Gab.Web.Controllers
{
    public class FeedsController : Controller
    {
        private readonly Client _gab;

        public FeedsController(Gab.Client gab)
        {
            _gab = gab;
        }

        public async Task<IActionResult> MainFeed()
        {
            var model = await _gab.MainFeed(); 

            return View(model);
        }

        public async Task<IActionResult> UserFeed()
        {
            var model = await _gab.UserFeed("AgendaOfEvil"); 

            return View(model);
        }
    }
}

Gab.Web/Controllers/GroupsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Gab.Web.Controllers
{
    public class GroupsController : Controller
    {
        private readonly Client _gab;

        public GroupsController(Gab.Client gab)
        {
            _gab = gab;
        }

        public async Task<IActionResult> PopularGroups()
        {
            var model = await _gab.PopularGroups(); 

            return View(model);
        }

        public async Task<IActionResult> GroupDetails()
        {
            var model = await _gab.GroupDetails(Guid.Parse("f8f914da-4423-4f0b-abb0-9e289cad8413")); 

            return View(model);
        }

        public async Task<IActionResult> GroupUsers()
        {
            var model = await _gab.GroupUsers(Guid.Parse("f8f914da-4423-4f0b-abb0-9e289cad8413")); 

            return View(model.Data);
        }

        public async Task<IActionResult> GroupModerationLogs()
        {
            var model = await _gab.GroupModerationLogs(Guid.Parse("f8f914da-4423-4f0b-abb0-9e289cad8413")); 

            return View(model);
        } 
    }
}

Gab.Web/Controllers/PostsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Gab.Web.Controllers
{
    public class PostsController : Controller
    {
        private readonly Client _gab;

        public PostsController(Gab.Client gab)
        {
            _gab = gab;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _gab.CreatePost(DateTimeOffset.UtcNow.ToString("F"));

            return View(model);
        }
    }
}

Gab.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Gab.Web.Controllers
{
    [Route("[controller]")]
    public class UsersController : Controller
    {
        private readonly Client _gab;

        public UsersController(Gab.Client gab)
        {
            _gab = gab;
        }

        [Route("[action]")]
        public async Task<IActionResult> Me()
        {
            var model = await _gab.UserDetails();

            return View(model);
        }

        [Route("{username}")]
        public async Task<IActionResult> User(string username)
        {
            var model = await _gab.UserDetails(username);

            return View(model);
        }

        [Route("[action]/{username}")]
        public async Task<IActionResult> Followers(string username)
        {
            var model = await _gab.Followers(username);

            return View(model);
        }

        [Route("[action]/{username}")]
        public async Task<IActionResult> Followed(string username)
        {
            var model = await _gab.Followed(username);

            return View(model);
        }
    }
}

Gab.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gab.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🐸 Gab.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Users
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Me" asp-route-username="">Logged-in User's Details</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="User" asp-route-username="RealTrumpTweets">User Details for {UserName}</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Followers" asp-route-username="AgendaOfEvil">Followers</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Followed" asp-route-username="AgendaOfEvil">Followed</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Feeds" asp-action="Index">Feeds</a>
                            </li>*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Feeds
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Feeds" asp-action="MainFeed">Main Feed</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Feeds" asp-action="UserFeed">User Feed</a>
                            </div>
                        </li>

                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Popular" asp-action="Index">Popular</a>
                            </li>*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Popular
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Popular" asp-action="PopularFeed">Popular Feed</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Popular" asp-action="PopularUsers">Popular Users</a>
                            </div>
                        </li>

                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Engaging" asp-action="Index">Engaging</a>
                            </li>*@


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Engaging
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Engaging" asp-action="Follow">Follow User</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Engaging" asp-action="UnFollow">UnFollow User</a>
                            </div>
                        </li>


                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reacting" asp-action="Index">Reacting</a>
                            </li>*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Reacting
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="UpVote">UpVote</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="DownVote">DownVote</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="RePost">RePost</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="RemoveUpVote">Remove UpVote</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="RemoveDownVote">Remove DownVote</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="RemoveRePost">Remove RePost</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Reacting" asp-action="PostDetails">Post Details</a>
                            </div>
                        </li>

                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                            </li>*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Groups
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Groups" asp-action="PopularGroups">Popular Groups</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Groups" asp-action="GroupDetails">Group Details</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Groups" asp-action="GroupUsers">Group Users</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Groups" asp-action="GroupModerationLogs">Group Moderation Logs</a>
                            </div>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2018 - Gab.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/js/jquery.js"></script>
        <script src="~/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/js/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>